### ISSUE TITLE
On a surface tablet this puts the computer to sleep

### ISSUE THREAD

**Issue by bakerboy908** [SmilyOrg/screenmqtt#1]
Title says its all really, sending OFF puts the computer to sleep, and because its sleeping no ON is received until it wakes up again

**Comment by SmilyOrg** [comment]
Interesting!

Ahh.. my documentation on this is really bad, but I believe you can either send the OFF to the whole computer (all screens, uses a standard way to turn off all display) or to individual monitors (which sends the "turn off" signal to the screen directly). Do both put it to sleep? 

Alternatively you could look into some sort of a Wake-on-lan functionality to wake it back up.
